# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 491, 270))
        self.frame.setStyleSheet("background-color:#fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 40, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 181, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../exchanging.png"))
        self.label_2.setObjectName("label_2")
        self.input_v = QtWidgets.QLineEdit(self.centralwidget)
        self.input_v.setGeometry(QtCore.QRect(50, 320, 380, 55))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_v.setFont(font)
        self.input_v.setStyleSheet("background-color:#22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white\n"
"")
        self.input_v.setAlignment(QtCore.Qt.AlignCenter)
        self.input_v.setObjectName("input_v")
        self.input_d = QtWidgets.QLineEdit(self.centralwidget)
        self.input_d.setGeometry(QtCore.QRect(50, 410, 380, 55))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_d.setFont(font)
        self.input_d.setStyleSheet("background-color:#22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white\n"
"")
        self.input_d.setAlignment(QtCore.Qt.AlignCenter)
        self.input_d.setObjectName("input_d")
        self.outpu_d = QtWidgets.QLineEdit(self.centralwidget)
        self.outpu_d.setGeometry(QtCore.QRect(50, 500, 380, 55))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.outpu_d.setFont(font)
        self.outpu_d.setStyleSheet("background-color:#22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white\n"
"")
        self.outpu_d.setAlignment(QtCore.Qt.AlignCenter)
        self.outpu_d.setObjectName("outpu_d")
        self.output_v = QtWidgets.QLineEdit(self.centralwidget)
        self.output_v.setGeometry(QtCore.QRect(50, 590, 380, 55))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_v.setFont(font)
        self.output_v.setStyleSheet("background-color:#22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white\n"
"")
        self.output_v.setAlignment(QtCore.Qt.AlignCenter)
        self.output_v.setObjectName("output_v")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 670, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #fd5d5b;\n"
"    border-radius: 30;\n"
"}\n"
"QPushButton: pressed{ \n"
"    background-color: #fa4244;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "КОНВЕРТЕР ВАЛЮТ"))
        self.input_v.setText(_translate("MainWindow", "1000"))
        self.input_d.setText(_translate("MainWindow", "1000"))
        self.outpu_d.setText(_translate("MainWindow", "1000"))
        self.output_v.setText(_translate("MainWindow", "1000"))
        self.pushButton.setText(_translate("MainWindow", "Конвертировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
